import { FormEvent, useMemo, useState, type ReactNode } from "react";
import { BarChart3, Bell, BookOpen, CalendarDays, CheckCircle2, ChevronLeft, ClipboardCheck, GraduationCap, LayoutDashboard, LogOut, Menu, Pencil, Plus, Search, Settings, Trash2, Users, WalletCards, X, FileText, UserCog, Clock3 } from "lucide-react";

type Role = "admin" | "teacher" | "accountant" | "student" | "parent";
type Status = "Active" | "Inactive";
type Student = { id:number; name:string; father:string; className:string; section:string; roll:string; phone:string; status:Status };
type Teacher = { id:number; name:string; email:string; phone:string; subject:string; classes:string; status:Status };
type SchoolClass = { id:number; name:string; sections:string; teacher:string; students:number };
type Subject = { id:number; name:string; code:string; className:string; teacher:string };
type Attendance = { id:number; student:string; className:string; section:string; date:string; status:"Present"|"Absent"|"Late" };
type Fee = { id:number; student:string; invoice:string; amount:number; paid:number; due:string; status:"Paid"|"Pending"|"Overdue" };
type Exam = { id:number; name:string; className:string; start:string; end:string; status:"Scheduled"|"Ongoing"|"Completed" };
type Notice = { id:number; title:string; audience:string; date:string; status:"Published"|"Draft" };
type User = { id:number; name:string; email:string; role:Role; status:Status };

const demoUsers = [
 {email:"admin@brightvision.edu",password:"admin123",name:"Haroon Khan",role:"admin" as Role},
 {email:"teacher@brightvision.edu",password:"teacher123",name:"Ayesha Siddiqui",role:"teacher" as Role},
 {email:"accounts@brightvision.edu",password:"account123",name:"Faizan Sattar",role:"accountant" as Role},
 {email:"student@brightvision.edu",password:"student123",name:"Ali Khan",role:"student" as Role},
 {email:"parent@brightvision.edu",password:"parent123",name:"Muhammad Khan",role:"parent" as Role},
];
const initialStudents:Student[]=[
 {id:1,name:"Ali Khan",father:"Muhammad Khan",className:"Class 5",section:"A",roll:"01",phone:"+92 300 1112233",status:"Active"},{id:2,name:"Fatima Raza",father:"Nasir Raza",className:"Class 3",section:"B",roll:"02",phone:"+92 301 2223344",status:"Active"},{id:3,name:"Hassan Sheikh",father:"Abdul Sheikh",className:"Class 7",section:"A",roll:"03",phone:"+92 302 3334455",status:"Active"},{id:4,name:"Zainab Iqbal",father:"Shahid Iqbal",className:"Class 2",section:"A",roll:"04",phone:"+92 303 4445566",status:"Active"},{id:5,name:"Usman Butt",father:"Tariq Butt",className:"Class 6",section:"B",roll:"05",phone:"+92 304 5556677",status:"Inactive"},{id:6,name:"Maryam Javed",father:"Aslam Chaudhry",className:"Class 4",section:"A",roll:"06",phone:"+92 305 6667788",status:"Active"}
];
const initialTeachers:Teacher[]=[
 {id:1,name:"Ayesha Siddiqui",email:"ayesha@brightvision.edu",phone:"+92 300 1122334",subject:"English",classes:"Nursery, Class 1",status:"Active"},{id:2,name:"Imran Haider",email:"imran@brightvision.edu",phone:"+92 301 2233445",subject:"Mathematics",classes:"Class 1, Class 2",status:"Active"},{id:3,name:"Sana Malik",email:"sana@brightvision.edu",phone:"+92 302 3344556",subject:"Science",classes:"Class 2, Class 3",status:"Active"},{id:4,name:"Bilal Ahmed",email:"bilal@brightvision.edu",phone:"+92 303 4455667",subject:"Urdu",classes:"Class 3",status:"Active"},{id:5,name:"Hina Qureshi",email:"hina@brightvision.edu",phone:"+92 304 5566778",subject:"Islamiat",classes:"Class 4",status:"Active"},{id:6,name:"Kamran Yousuf",email:"kamran@brightvision.edu",phone:"+92 305 6677889",subject:"Computer Science",classes:"Class 5, Class 6",status:"Active"},{id:7,name:"Nadia Farooq",email:"nadia@brightvision.edu",phone:"+92 306 7788990",subject:"Social Studies",classes:"Class 6",status:"Inactive"},{id:8,name:"Rehan Aslam",email:"rehan@brightvision.edu",phone:"+92 307 8899001",subject:"Mathematics",classes:"Class 7",status:"Active"}
];
const initialClasses:SchoolClass[]=[{id:1,name:"Nursery",sections:"A, B",teacher:"Ayesha Siddiqui",students:42},{id:2,name:"Class 1",sections:"A, B",teacher:"Imran Haider",students:58},{id:3,name:"Class 2",sections:"A, B",teacher:"Sana Malik",students:55},{id:4,name:"Class 3",sections:"A, B, C",teacher:"Bilal Ahmed",students:76},{id:5,name:"Class 4",sections:"A, B",teacher:"Hina Qureshi",students:61},{id:6,name:"Class 5",sections:"A, B",teacher:"Kamran Yousuf",students:64},{id:7,name:"Class 6",sections:"A, B",teacher:"Nadia Farooq",students:52},{id:8,name:"Class 7",sections:"A",teacher:"Rehan Aslam",students:34}];
const initialSubjects:Subject[]=[{id:1,name:"English",code:"ENG-101",className:"Class 1",teacher:"Ayesha Siddiqui"},{id:2,name:"Mathematics",code:"MAT-101",className:"Class 1",teacher:"Imran Haider"},{id:3,name:"Science",code:"SCI-101",className:"Class 2",teacher:"Sana Malik"},{id:4,name:"Urdu",code:"URD-101",className:"Class 3",teacher:"Bilal Ahmed"},{id:5,name:"Islamiat",code:"ISL-101",className:"Class 4",teacher:"Hina Qureshi"},{id:6,name:"Computer Science",code:"CS-101",className:"Class 5",teacher:"Kamran Yousuf"},{id:7,name:"Social Studies",code:"SST-101",className:"Class 6",teacher:"Nadia Farooq"}];
const initialAttendance:Attendance[]=initialStudents.map((s,i)=>({id:i+1,student:s.name,className:s.className,section:s.section,date:"2026-08-17",status:i===2?"Absent":i===4?"Late":"Present"}));
const initialFees:Fee[]=[{id:1,student:"Ali Khan",invoice:"RCP-1001",amount:4500,paid:4500,due:"25/08/2026",status:"Paid"},{id:2,student:"Fatima Raza",invoice:"RCP-1002",amount:4000,paid:0,due:"25/08/2026",status:"Pending"},{id:3,student:"Hassan Sheikh",invoice:"RCP-1003",amount:5500,paid:0,due:"10/07/2026",status:"Overdue"},{id:4,student:"Zainab Iqbal",invoice:"RCP-1004",amount:4000,paid:4000,due:"25/08/2026",status:"Paid"}];
const initialExams:Exam[]=[{id:1,name:"First Term 2026",className:"Class 3",start:"05/05/2026",end:"14/05/2026",status:"Completed"},{id:2,name:"Mid Term 2026",className:"Class 3",start:"01/09/2026",end:"10/09/2026",status:"Scheduled"},{id:3,name:"Mid Term 2026",className:"Class 5",start:"01/09/2026",end:"10/09/2026",status:"Scheduled"}];
const initialNotices:Notice[]=[{id:1,title:"Parent–Teacher Meeting",audience:"Parents",date:"15/08/2026",status:"Published"},{id:2,title:"Independence Day Assembly",audience:"All",date:"14/08/2026",status:"Published"},{id:3,title:"Mid Term Datesheet Released",audience:"Students",date:"10/08/2026",status:"Published"},{id:4,title:"Staff Training Workshop",audience:"Teachers",date:"08/08/2026",status:"Draft"}];
const initialAccounts:User[]=[{id:1,name:"Haroon Khan",email:"admin@brightvision.edu",role:"admin",status:"Active"},{id:2,name:"Ayesha Siddiqui",email:"teacher@brightvision.edu",role:"teacher",status:"Active"},{id:3,name:"Faizan Sattar",email:"accounts@brightvision.edu",role:"accountant",status:"Active"},{id:4,name:"Ali Khan",email:"student@brightvision.edu",role:"student",status:"Active"},{id:5,name:"Muhammad Khan",email:"parent@brightvision.edu",role:"parent",status:"Active"}];

const nav=[ ["Dashboard",LayoutDashboard],["Students",GraduationCap],["Teachers",Users],["Classes",BookOpen],["Subjects",BookOpen],["Attendance",ClipboardCheck],["Fees",WalletCards],["Exams & Results",BarChart3],["Timetable",CalendarDays],["Notices",Bell],["Reports",FileText],["Users",UserCog],["Settings",Settings] ] as const;

export default function App(){const[user,setUser]=useState<typeof demoUsers[number]|null>(()=>{try{return JSON.parse(localStorage.getItem("bv_user")||"null")}catch{return null}});return user?<Portal user={user} onLogout={()=>{localStorage.removeItem("bv_user");setUser(null)}}/>:<Login onLogin={u=>{localStorage.setItem("bv_user",JSON.stringify(u));setUser(u)}}/>}
function Login({onLogin}:{onLogin:(u:typeof demoUsers[number])=>void}){const[email,setEmail]=useState("admin@brightvision.edu"),[password,setPassword]=useState("admin123"),[error,setError]=useState("");return <div className="login-page"><div className="login-card"><div className="login-brand"><div className="logo big">BV</div><div><h1>Bright Vision</h1><span>English School</span></div></div><h2>Welcome back</h2><p className="muted">School Management System</p><form onSubmit={(e:FormEvent)=>{e.preventDefault();const u=demoUsers.find(x=>x.email===email.trim().toLowerCase()&&x.password===password);u?onLogin(u):setError("Invalid email or password. Admin: admin@brightvision.edu / admin123")}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><div className="login-options"><label className="check"><input type="checkbox" defaultChecked/> Remember me</label><button type="button" className="link">Forgot password?</button></div>{error&&<div className="error">{error}</div>}<button className="primary full">Login</button></form><div className="demo-box"><strong>Demo accounts</strong><span>Admin · Teacher · Accountant · Student · Parent</span></div></div></div>}

function Portal({user,onLogout}:{user:typeof demoUsers[number];onLogout:()=>void}){const[open,setOpen]=useState(true),[active,setActive]=useState("Dashboard"),[students,setStudents]=useState(initialStudents),[teachers,setTeachers]=useState(initialTeachers),[classes,setClasses]=useState(initialClasses),[subjects,setSubjects]=useState(initialSubjects),[attendance,setAttendance]=useState(initialAttendance),[fees,setFees]=useState(initialFees),[exams,setExams]=useState(initialExams),[notices,setNotices]=useState(initialNotices),[accounts,setAccounts]=useState(initialAccounts),[modal,setModal]=useState<null|string>(null),[edit,setEdit]=useState<any>(null);
 const isAdmin=user.role==="admin", canStudent=user.role==="admin"||user.role==="teacher", canAccount=user.role==="admin"||user.role==="accountant"; const choose=(x:string)=>{setActive(x);setModal(null);setEdit(null)};
 return <div className="app"><aside className={`sidebar ${open?"":"collapsed"}`}><div className="brand"><div className="logo">BV</div>{open&&<div><strong>Bright Vision</strong><span>English School</span></div>}</div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>choose(label)}><Icon size={19}/>{open&&label}</button>)}</nav><div className="sidebar-bottom"><div className="school-mini"><strong>{open?user.name:""}</strong>{open&&<span>{user.role}</span>}</div><button className="logout" onClick={onLogout}><LogOut size={19}/>{open&&"Logout"}</button></div></aside><main className="main"><header><button className="icon-btn" onClick={()=>setOpen(!open)}>{open?<ChevronLeft/>:<Menu/>}</button><div className="header-title"><span>Bright Vision English School</span><small>Academic Session 2026 – 2027</small></div><div className="header-user">{user.name}</div><button className="icon-btn"><Bell size={20}/></button></header><section className="content">
 {active==="Dashboard"&&<Dashboard user={user} students={students} fees={fees}/>} 
 {active==="Students"&&<StudentsPage data={students} canManage={canStudent} onAdd={()=>{setEdit(null);setModal("student")}} onEdit={x=>{setEdit(x);setModal("student")}} onDelete={id=>setStudents(a=>a.filter(x=>x.id!==id))}/>} 
 {active==="Teachers"&&<TeachersPage data={teachers} canManage={isAdmin} onAdd={()=>{setEdit(null);setModal("teacher")}} onEdit={x=>{setEdit(x);setModal("teacher")}} onDelete={id=>setTeachers(a=>a.filter(x=>x.id!==id))}/>} 
 {active==="Classes"&&<ClassesPage data={classes} canManage={isAdmin} onAdd={()=>{setEdit(null);setModal("class")}} onEdit={x=>{setEdit(x);setModal("class")}} onDelete={id=>setClasses(a=>a.filter(x=>x.id!==id))}/>} 
 {active==="Subjects"&&<SubjectsPage data={subjects} canManage={isAdmin} onAdd={()=>{setEdit(null);setModal("subject")}} onEdit={x=>{setEdit(x);setModal("subject")}} onDelete={id=>setSubjects(a=>a.filter(x=>x.id!==id))}/>} 
 {active==="Attendance"&&<AttendancePage data={attendance} canManage={canStudent} onChange={(id,status)=>setAttendance(a=>a.map(x=>x.id===id?{...x,status}:x))}/>} 
 {active==="Fees"&&<FeesPage data={fees} canManage={canAccount} onPay={id=>setFees(a=>a.map(x=>x.id===id?{...x,paid:x.amount,status:"Paid"}:x))}/>} 
 {active==="Exams & Results"&&<ExamsPage data={exams} canManage={isAdmin} onAdd={()=>{setEdit(null);setModal("exam")}} onEdit={x=>{setEdit(x);setModal("exam")}} onDelete={id=>setExams(a=>a.filter(x=>x.id!==id))}/>} 
 {active==="Timetable"&&<TimetablePage/>} 
 {active==="Notices"&&<NoticesPage data={notices} canManage={isAdmin} onAdd={()=>{setEdit(null);setModal("notice")}} onEdit={x=>{setEdit(x);setModal("notice")}} onDelete={id=>setNotices(a=>a.filter(x=>x.id!==id))}/>} 
 {active==="Reports"&&<ReportsPage students={students} fees={fees} attendance={attendance}/>} 
 {active==="Users"&&<UsersPage data={accounts} canManage={isAdmin} onAdd={()=>{setEdit(null);setModal("user")}} onEdit={x=>{setEdit(x);setModal("user")}} onDelete={id=>setAccounts(a=>a.filter(x=>x.id!==id))}/>} 
 {active==="Settings"&&<SettingsPage/>}
 </section></main>
 {modal==="student"&&<StudentForm item={edit} onClose={()=>setModal(null)} onSave={x=>{setStudents(a=>x.id?a.map(v=>v.id===x.id?x:v):[...a,{...x,id:Date.now()}]);setModal(null)}}/>}
 {modal==="teacher"&&<TeacherForm item={edit} onClose={()=>setModal(null)} onSave={x=>{setTeachers(a=>x.id?a.map(v=>v.id===x.id?x:v):[...a,{...x,id:Date.now()}]);setModal(null)}}/>}
 {modal==="class"&&<ClassForm item={edit} onClose={()=>setModal(null)} onSave={x=>{setClasses(a=>x.id?a.map(v=>v.id===x.id?x:v):[...a,{...x,id:Date.now()}]);setModal(null)}}/>}
 {modal==="subject"&&<SubjectForm item={edit} onClose={()=>setModal(null)} onSave={x=>{setSubjects(a=>x.id?a.map(v=>v.id===x.id?x:v):[...a,{...x,id:Date.now()}]);setModal(null)}}/>}
 {modal==="exam"&&<ExamForm item={edit} onClose={()=>setModal(null)} onSave={x=>{setExams(a=>x.id?a.map(v=>v.id===x.id?x:v):[...a,{...x,id:Date.now()}]);setModal(null)}}/>}
 {modal==="notice"&&<NoticeForm item={edit} onClose={()=>setModal(null)} onSave={x=>{setNotices(a=>x.id?a.map(v=>v.id===x.id?x:v):[...a,{...x,id:Date.now()}]);setModal(null)}}/>}
 {modal==="user"&&<UserForm item={edit} onClose={()=>setModal(null)} onSave={x=>{setAccounts(a=>x.id?a.map(v=>v.id===x.id?x:v):[...a,{...x,id:Date.now()}]);setModal(null)}}/>}
 </div>}

function Dashboard({user,students,fees}:{user:any;students:Student[];fees:Fee[]}){const paid=fees.filter(x=>x.status==="Paid").reduce((s,x)=>s+x.amount,0),pending=fees.filter(x=>x.status!=="Paid").reduce((s,x)=>s+x.amount,0);return <><PageHead title="Dashboard" desc={`Welcome back, ${user.name}. Here is today's school overview.`}/><div className="stats"><Stat title="Total Students" value="486" icon={<GraduationCap/>}/><Stat title="Total Teachers" value="8" icon={<Users/>}/><Stat title="Total Classes" value="8" icon={<BookOpen/>}/><Stat title="Today's Attendance" value="92%" icon={<ClipboardCheck/>}/><Stat title="Today's Fee Collection" value={`PKR ${paid.toLocaleString()}`} icon={<WalletCards/>}/><Stat title="Pending Fees" value={`PKR ${pending.toLocaleString()}`} icon={<Clock3/>}/></div><div className="grid"><Panel title="Attendance Overview"><div className="attendance"><b>92%</b><span>Present today</span><div className="bar"><i style={{width:"92%"}}/></div><small>Present 447 · Late 18 · Absent 21</small></div></Panel><Panel title="Fee Overview"><div className="fee-row"><span>Collected</span><b>PKR {paid.toLocaleString()}</b></div><div className="fee-row"><span>Pending</span><b>PKR {pending.toLocaleString()}</b></div><div className="fee-row"><span>Overdue</span><b>PKR {fees.filter(x=>x.status==="Overdue").reduce((s,x)=>s+x.amount,0).toLocaleString()}</b></div></Panel></div><div className="grid"><Panel title="Recent Students">{students.slice(0,4).map(s=><div className="item" key={s.id}><strong>{s.name}</strong><span>{s.className} · Section {s.section}</span></div>)}</Panel><Panel title="Recent Notices"><div className="item"><strong>Parent–Teacher Meeting</strong><span>Today at 8:01 AM</span></div><div className="item"><strong>Independence Day Assembly</strong><span>14 Aug 2026</span></div><div className="item"><strong>Mid Term Datesheet Released</strong><span>10 Aug 2026</span></div></Panel></div></>}

function PageHead({title,desc,action}:{title:string;desc:string;action?:ReactNode}){return <div className="page-head"><div><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Panel({title,children}:{title:string;children:ReactNode}){return <div className="panel"><h2>{title}</h2>{children}</div>}
function Stat({title,value,icon}:{title:string;value:string;icon:ReactNode}){return <div className="stat"><div className="stat-icon">{icon}</div><span>{title}</span><strong>{value}</strong></div>}
function TablePage({title,desc,canManage,onAdd,query,setQuery,children}:{title:string;desc:string;canManage:boolean;onAdd:()=>void;query?:string;setQuery?:React.Dispatch<React.SetStateAction<string>>;children:ReactNode}){return <><PageHead title={title} desc={desc} action={canManage?<button className="primary" onClick={onAdd}><Plus size={17}/> Add {title.endsWith("s")?title.slice(0,-1):title}</button>:undefined}/><div className="panel table-panel"><div className="table-toolbar">{setQuery?<div className="search"><Search size={17}/><input placeholder={`Search ${title.toLowerCase()}...`} value={query} onChange={e=>setQuery(e.target.value)}/></div>:<div/>}<span>Live demo data</span></div><div className="table-wrap"><table>{children}</table></div></div></>}
function Actions({onEdit,onDelete}:{onEdit:()=>void;onDelete:()=>void}){return <div className="actions"><button className="icon-btn small" onClick={onEdit} title="Edit"><Pencil size={15}/></button><button className="icon-btn small danger" onClick={()=>{if(confirm("Are you sure you want to delete this record?"))onDelete()}} title="Delete"><Trash2 size={15}/></button></div>}
function StudentsPage({data,canManage,onAdd,onEdit,onDelete}:{data:Student[];canManage:boolean;onAdd:()=>void;onEdit:(x:Student)=>void;onDelete:(id:number)=>void}){const[q,setQ]=useState("");const f=useMemo(()=>data.filter(x=>`${x.name} ${x.father} ${x.className} ${x.roll}`.toLowerCase().includes(q.toLowerCase())),[data,q]);return <TablePage title="Students" desc="Manage admissions, student profiles, classes and contact details." canManage={canManage} onAdd={onAdd} query={q} setQuery={setQ}><thead><tr><th>Student</th><th>Father</th><th>Class</th><th>Roll</th><th>Phone</th><th>Status</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{f.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>BV-S-{String(x.id).padStart(4,"0")}</small></td><td>{x.father}</td><td>{x.className} · {x.section}</td><td>{x.roll}</td><td>{x.phone}</td><td><Badge value={x.status}/></td>{canManage&&<td><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x.id)}/></td>}</tr>)}</tbody></TablePage>}
function TeachersPage({data,canManage,onAdd,onEdit,onDelete}:{data:Teacher[];canManage:boolean;onAdd:()=>void;onEdit:(x:Teacher)=>void;onDelete:(id:number)=>void}){const[q,setQ]=useState("");const f=data.filter(x=>`${x.name} ${x.subject} ${x.email}`.toLowerCase().includes(q.toLowerCase()));return <TablePage title="Teachers" desc="Manage staff profiles, subjects and class assignments." canManage={canManage} onAdd={onAdd} query={q} setQuery={setQ}><thead><tr><th>Teacher</th><th>Subject</th><th>Classes</th><th>Phone</th><th>Status</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{f.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small>{x.email}</small></td><td>{x.subject}</td><td>{x.classes}</td><td>{x.phone}</td><td><Badge value={x.status}/></td>{canManage&&<td><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x.id)}/></td>}</tr>)}</tbody></TablePage>}
function ClassesPage({data,canManage,onAdd,onEdit,onDelete}:{data:SchoolClass[];canManage:boolean;onAdd:()=>void;onEdit:(x:SchoolClass)=>void;onDelete:(id:number)=>void}){return <TablePage title="Classes" desc="Manage classes, sections, class teachers and student counts." canManage={canManage} onAdd={onAdd}><thead><tr><th>Class</th><th>Sections</th><th>Class Teacher</th><th>Students</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.sections}</td><td>{x.teacher}</td><td>{x.students}</td>{canManage&&<td><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x.id)}/></td>}</tr>)}</tbody></TablePage>}
function SubjectsPage({data,canManage,onAdd,onEdit,onDelete}:{data:Subject[];canManage:boolean;onAdd:()=>void;onEdit:(x:Subject)=>void;onDelete:(id:number)=>void}){return <TablePage title="Subjects" desc="Manage curriculum subjects and teacher assignments." canManage={canManage} onAdd={onAdd}><thead><tr><th>Subject</th><th>Code</th><th>Class</th><th>Teacher</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.code}</td><td>{x.className}</td><td>{x.teacher}</td>{canManage&&<td><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x.id)}/></td>}</tr>)}</tbody></TablePage>}
function AttendancePage({data,canManage,onChange}:{data:Attendance[];canManage:boolean;onChange:(id:number,status:Attendance["status"])=>void}){return <><PageHead title="Attendance" desc="Record and review daily student attendance."/><div className="panel table-panel"><div className="table-toolbar"><span>{data.filter(x=>x.status==="Present").length} present · {data.filter(x=>x.status==="Absent").length} absent · {data.filter(x=>x.status==="Late").length} late</span><strong>17/08/2026</strong></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Section</th><th>Status</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.student}</strong></td><td>{x.className}</td><td>{x.section}</td><td>{canManage?<select className="inline-select" value={x.status} onChange={e=>onChange(x.id,e.target.value as Attendance["status"])}><option>Present</option><option>Absent</option><option>Late</option></select>:<Badge value={x.status}/>}</td></tr>)}</tbody></table></div></div></>}
function FeesPage({data,canManage,onPay}:{data:Fee[];canManage:boolean;onPay:(id:number)=>void}){return <><PageHead title="Fees" desc="Track invoices, payments, pending and overdue school fees."/><div className="stats"><Stat title="Collected" value={`PKR ${data.reduce((s,x)=>s+x.paid,0).toLocaleString()}`} icon={<CheckCircle2/>}/><Stat title="Pending" value={`PKR ${data.filter(x=>x.status==="Pending").reduce((s,x)=>s+x.amount,0).toLocaleString()}`} icon={<WalletCards/>}/><Stat title="Overdue" value={`PKR ${data.filter(x=>x.status==="Overdue").reduce((s,x)=>s+x.amount,0).toLocaleString()}`} icon={<Bell/>}/></div><div className="panel table-panel" style={{marginTop:16}}><div className="table-wrap"><table><thead><tr><th>Student</th><th>Invoice</th><th>Amount</th><th>Paid</th><th>Due Date</th><th>Status</th>{canManage&&<th>Action</th>}</tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.student}</strong></td><td>{x.invoice}</td><td>PKR {x.amount.toLocaleString()}</td><td>PKR {x.paid.toLocaleString()}</td><td>{x.due}</td><td><Badge value={x.status}/></td>{canManage&&<td>{x.status!=="Paid"&&<button className="secondary compact" onClick={()=>onPay(x.id)}>Mark Paid</button>}</td>}</tr>)}</tbody></table></div></div></>}
function ExamsPage({data,canManage,onAdd,onEdit,onDelete}:{data:Exam[];canManage:boolean;onAdd:()=>void;onEdit:(x:Exam)=>void;onDelete:(id:number)=>void}){return <TablePage title="Exams & Results" desc="Schedule examinations and manage academic assessment cycles." canManage={canManage} onAdd={onAdd}><thead><tr><th>Exam</th><th>Class</th><th>Start</th><th>End</th><th>Status</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.className}</td><td>{x.start}</td><td>{x.end}</td><td><Badge value={x.status}/></td>{canManage&&<td><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x.id)}/></td>}</tr>)}</tbody></TablePage>}
function TimetablePage(){const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];return <><PageHead title="Timetable" desc="Weekly class schedule for teachers and students."/><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Period</th>{days.map(d=><th key={d}>{d}</th>)}</tr></thead><tbody>{[1,2,3,4,5,6].map(p=><tr key={p}><td><strong>{p}</strong></td>{days.map((d,i)=><td key={d}>{["English","Mathematics","Science","Urdu","Computer","Islamiat"][(p+i)%6]}<small>Class {((p+i)%7)+1} · R-{100+p}</small></td>)}</tr>)}</tbody></table></div></div></>}
function NoticesPage({data,canManage,onAdd,onEdit,onDelete}:{data:Notice[];canManage:boolean;onAdd:()=>void;onEdit:(x:Notice)=>void;onDelete:(id:number)=>void}){return <TablePage title="Notices" desc="Publish announcements for students, parents and staff." canManage={canManage} onAdd={onAdd}><thead><tr><th>Title</th><th>Audience</th><th>Date</th><th>Status</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.title}</strong></td><td>{x.audience}</td><td>{x.date}</td><td><Badge value={x.status}/></td>{canManage&&<td><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x.id)}/></td>}</tr>)}</tbody></TablePage>}
function ReportsPage({students,fees,attendance}:{students:Student[];fees:Fee[];attendance:Attendance[]}){const present=attendance.filter(x=>x.status==="Present").length;return <><PageHead title="Reports" desc="School-wide summary reports for administration."/><div className="report-grid"><Panel title="Student Summary"><ReportRow label="Total Students" value="486"/><ReportRow label="Active in demo" value={String(students.filter(x=>x.status==="Active").length)}/><ReportRow label="Inactive in demo" value={String(students.filter(x=>x.status==="Inactive").length)}/></Panel><Panel title="Attendance Summary"><ReportRow label="Present" value={`${present}`}/><ReportRow label="Absent" value={`${attendance.filter(x=>x.status==="Absent").length}`}/><ReportRow label="Late" value={`${attendance.filter(x=>x.status==="Late").length}`}/></Panel><Panel title="Finance Summary"><ReportRow label="Invoices" value={String(fees.length)}/><ReportRow label="Paid invoices" value={String(fees.filter(x=>x.status==="Paid").length)}/><ReportRow label="Outstanding" value={`PKR ${fees.filter(x=>x.status!=="Paid").reduce((s,x)=>s+x.amount,0).toLocaleString()}`}/></Panel></div></>}
function ReportRow({label,value}:{label:string;value:string}){return <div className="fee-row"><span>{label}</span><b>{value}</b></div>}
function UsersPage({data,canManage,onAdd,onEdit,onDelete}:{data:User[];canManage:boolean;onAdd:()=>void;onEdit:(x:User)=>void;onDelete:(id:number)=>void}){return <TablePage title="Users" desc="Manage accounts and roles for the school portal." canManage={canManage} onAdd={onAdd}><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Status</th>{canManage&&<th>Actions</th>}</tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{x.email}</td><td><span className="role-pill">{x.role}</span></td><td><Badge value={x.status}/></td>{canManage&&<td><Actions onEdit={()=>onEdit(x)} onDelete={()=>onDelete(x.id)}/></td>}</tr>)}</tbody></TablePage>}
function SettingsPage(){const[saved,setSaved]=useState(false);return <><PageHead title="Settings" desc="Configure school identity and academic session."/><div className="panel settings-panel"><h2>School Profile</h2><div className="form-grid"><label>School Name<input defaultValue="Bright Vision English School"/></label><label>Principal Name<input defaultValue="Prof. Zubair Hameed"/></label><label>Phone<input defaultValue="+92 21 3456 7890"/></label><label>Email<input defaultValue="info@brightvision.edu"/></label><label className="wide">Address<input defaultValue="12-C, Main Boulevard, Gulshan-e-Iqbal, Karachi"/></label><label>Academic Session<select defaultValue="2026 – 2027"><option>2026 – 2027</option><option>2027 – 2028</option></select></label><label>Currency<select defaultValue="PKR"><option>PKR</option><option>USD</option></select></label></div><div className="modal-actions"><button className="primary" onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),1800)}}>{saved?"Saved ✓":"Save Settings"}</button></div></div></>}
function Badge({value}:{value:string}){return <span className={`badge ${value.toLowerCase().replace(/\s/g,"-")}`}>{value}</span>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>Enter the required information.</p></div><button className="icon-btn" onClick={onClose}><X size={20}/></button></div>{children}</div></div>}
function ModalActions({onClose}:{onClose:()=>void}){return <div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Save</button></div>}
function StudentForm({item,onClose,onSave}:{item:Student|null;onClose:()=>void;onSave:(x:Student)=>void}){const[f,setF]=useState<Student>(item||{id:0,name:"",father:"",className:"Class 1",section:"A",roll:"",phone:"",status:"Active"});const set=(k:keyof Student,v:string)=>setF(x=>({...x,[k]:v} as Student));return <Modal title={item?"Edit Student":"Add Student"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="form-grid"><label>Full Name<input value={f.name} onChange={e=>set("name",e.target.value)} required/></label><label>Father Name<input value={f.father} onChange={e=>set("father",e.target.value)} required/></label><label>Class<select value={f.className} onChange={e=>set("className",e.target.value)}>{["Nursery",...Array.from({length:7},(_,i)=>`Class ${i+1}`)].map(x=><option key={x}>{x}</option>)}</select></label><label>Section<select value={f.section} onChange={e=>set("section",e.target.value)}><option>A</option><option>B</option><option>C</option></select></label><label>Roll Number<input value={f.roll} onChange={e=>set("roll",e.target.value)} required/></label><label>Phone<input value={f.phone} onChange={e=>set("phone",e.target.value)} required/></label><label>Status<select value={f.status} onChange={e=>set("status",e.target.value as Status)}><option>Active</option><option>Inactive</option></select></label></div><ModalActions onClose={onClose}/></form></Modal>}
function TeacherForm({item,onClose,onSave}:{item:Teacher|null;onClose:()=>void;onSave:(x:Teacher)=>void}){const[f,setF]=useState<Teacher>(item||{id:0,name:"",email:"",phone:"",subject:"English",classes:"Class 1",status:"Active"});const set=(k:keyof Teacher,v:string)=>setF(x=>({...x,[k]:v} as Teacher));return <Modal title={item?"Edit Teacher":"Add Teacher"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="form-grid"><label>Full Name<input value={f.name} onChange={e=>set("name",e.target.value)} required/></label><label>Email<input type="email" value={f.email} onChange={e=>set("email",e.target.value)} required/></label><label>Phone<input value={f.phone} onChange={e=>set("phone",e.target.value)} required/></label><label>Subject<input value={f.subject} onChange={e=>set("subject",e.target.value)} required/></label><label>Classes<input value={f.classes} onChange={e=>set("classes",e.target.value)} required/></label><label>Status<select value={f.status} onChange={e=>set("status",e.target.value as Status)}><option>Active</option><option>Inactive</option></select></label></div><ModalActions onClose={onClose}/></form></Modal>}
function ClassForm({item,onClose,onSave}:{item:SchoolClass|null;onClose:()=>void;onSave:(x:SchoolClass)=>void}){const[f,setF]=useState<SchoolClass>(item||{id:0,name:"",sections:"A, B",teacher:"",students:0});const set=(k:keyof SchoolClass,v:string|number)=>setF(x=>({...x,[k]:v} as SchoolClass));return <Modal title={item?"Edit Class":"Add Class"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="form-grid"><label>Class Name<input value={f.name} onChange={e=>set("name",e.target.value)} required/></label><label>Sections<input value={f.sections} onChange={e=>set("sections",e.target.value)} required/></label><label>Class Teacher<input value={f.teacher} onChange={e=>set("teacher",e.target.value)} required/></label><label>Students<input type="number" min="0" value={f.students} onChange={e=>set("students",Number(e.target.value))}/></label></div><ModalActions onClose={onClose}/></form></Modal>}
function SubjectForm({item,onClose,onSave}:{item:Subject|null;onClose:()=>void;onSave:(x:Subject)=>void}){const[f,setF]=useState<Subject>(item||{id:0,name:"",code:"",className:"Class 1",teacher:""});const set=(k:keyof Subject,v:string)=>setF(x=>({...x,[k]:v} as Subject));return <Modal title={item?"Edit Subject":"Add Subject"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="form-grid"><label>Subject Name<input value={f.name} onChange={e=>set("name",e.target.value)} required/></label><label>Subject Code<input value={f.code} onChange={e=>set("code",e.target.value)} required/></label><label>Class<input value={f.className} onChange={e=>set("className",e.target.value)} required/></label><label>Teacher<input value={f.teacher} onChange={e=>set("teacher",e.target.value)} required/></label></div><ModalActions onClose={onClose}/></form></Modal>}
function ExamForm({item,onClose,onSave}:{item:Exam|null;onClose:()=>void;onSave:(x:Exam)=>void}){const[f,setF]=useState<Exam>(item||{id:0,name:"",className:"Class 1",start:"",end:"",status:"Scheduled"});const set=(k:keyof Exam,v:string)=>setF(x=>({...x,[k]:v} as Exam));return <Modal title={item?"Edit Exam":"Add Exam"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="form-grid"><label>Exam Name<input value={f.name} onChange={e=>set("name",e.target.value)} required/></label><label>Class<input value={f.className} onChange={e=>set("className",e.target.value)} required/></label><label>Start Date<input value={f.start} onChange={e=>set("start",e.target.value)} required/></label><label>End Date<input value={f.end} onChange={e=>set("end",e.target.value)} required/></label><label>Status<select value={f.status} onChange={e=>set("status",e.target.value as Exam["status"])}><option>Scheduled</option><option>Ongoing</option><option>Completed</option></select></label></div><ModalActions onClose={onClose}/></form></Modal>}
function NoticeForm({item,onClose,onSave}:{item:Notice|null;onClose:()=>void;onSave:(x:Notice)=>void}){const[f,setF]=useState<Notice>(item||{id:0,title:"",audience:"All",date:"17/08/2026",status:"Published"});const set=(k:keyof Notice,v:string)=>setF(x=>({...x,[k]:v} as Notice));return <Modal title={item?"Edit Notice":"Create Notice"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="form-grid"><label>Title<input value={f.title} onChange={e=>set("title",e.target.value)} required/></label><label>Audience<select value={f.audience} onChange={e=>set("audience",e.target.value)}><option>All</option><option>Students</option><option>Parents</option><option>Teachers</option><option>Staff</option></select></label><label>Date<input value={f.date} onChange={e=>set("date",e.target.value)} required/></label><label>Status<select value={f.status} onChange={e=>set("status",e.target.value as Notice["status"])}><option>Published</option><option>Draft</option></select></label></div><ModalActions onClose={onClose}/></form></Modal>}
function UserForm({item,onClose,onSave}:{item:User|null;onClose:()=>void;onSave:(x:User)=>void}){const[f,setF]=useState<User>(item||{id:0,name:"",email:"",role:"teacher",status:"Active"});const set=(k:keyof User,v:string)=>setF(x=>({...x,[k]:v} as User));return <Modal title={item?"Edit User":"Add User"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="form-grid"><label>Name<input value={f.name} onChange={e=>set("name",e.target.value)} required/></label><label>Email<input type="email" value={f.email} onChange={e=>set("email",e.target.value)} required/></label><label>Role<select value={f.role} onChange={e=>set("role",e.target.value as Role)}><option value="admin">Admin</option><option value="teacher">Teacher</option><option value="accountant">Accountant</option><option value="student">Student</option><option value="parent">Parent</option></select></label><label>Status<select value={f.status} onChange={e=>set("status",e.target.value as Status)}><option>Active</option><option>Inactive</option></select></label></div><ModalActions onClose={onClose}/></form></Modal>}
