import { FormEvent, useMemo, useState } from "react";
import { BarChart3, Bell, BookOpen, CalendarDays, ChevronLeft, ClipboardCheck, GraduationCap, LayoutDashboard, LogOut, Menu, Pencil, Plus, Search, Settings, Trash2, Users, WalletCards, X } from "lucide-react";

type Role = "admin" | "teacher" | "accountant" | "student" | "parent";
type Status = "Active" | "Inactive";
type Student = { id:number; name:string; father:string; className:string; section:string; roll:string; phone:string; status:Status };
type Teacher = { id:number; name:string; email:string; subject:string; classes:string; status:Status };
type Attendance = { id:number; student:string; className:string; section:string; status:"Present"|"Absent"|"Late" };
type Fee = { id:number; student:string; invoice:string; amount:number; paid:number; due:string; status:"Paid"|"Pending"|"Overdue" };

const users = [
 {email:"admin@brightvision.edu",password:"admin123",name:"Haroon Khan",role:"admin" as Role},
 {email:"teacher@brightvision.edu",password:"teacher123",name:"Ayesha Siddiqui",role:"teacher" as Role},
 {email:"accounts@brightvision.edu",password:"account123",name:"Faizan Sattar",role:"accountant" as Role},
 {email:"student@brightvision.edu",password:"student123",name:"Ali Khan",role:"student" as Role},
 {email:"parent@brightvision.edu",password:"parent123",name:"Muhammad Khan",role:"parent" as Role},
];
const students:Student[] = [
 {id:1,name:"Ali Khan",father:"Muhammad Khan",className:"Class 5",section:"A",roll:"01",phone:"+92 300 1112233",status:"Active"},
 {id:2,name:"Fatima Raza",father:"Nasir Raza",className:"Class 3",section:"B",roll:"02",phone:"+92 301 2223344",status:"Active"},
 {id:3,name:"Hassan Sheikh",father:"Abdul Sheikh",className:"Class 7",section:"A",roll:"03",phone:"+92 302 3334455",status:"Active"},
 {id:4,name:"Zainab Iqbal",father:"Shahid Iqbal",className:"Class 2",section:"A",roll:"04",phone:"+92 303 4445566",status:"Active"},
 {id:5,name:"Usman Butt",father:"Tariq Butt",className:"Class 6",section:"B",roll:"05",phone:"+92 304 5556677",status:"Inactive"},
 {id:6,name:"Maryam Javed",father:"Aslam Chaudhry",className:"Class 4",section:"A",roll:"06",phone:"+92 305 6667788",status:"Active"},
];
const teachers:Teacher[] = [
 {id:1,name:"Ayesha Siddiqui",email:"ayesha@brightvision.edu",subject:"English",classes:"Nursery, Class 1",status:"Active"},
 {id:2,name:"Imran Haider",email:"imran@brightvision.edu",subject:"Mathematics",classes:"Class 1, Class 2",status:"Active"},
 {id:3,name:"Sana Malik",email:"sana@brightvision.edu",subject:"Science",classes:"Class 2, Class 3",status:"Active"},
 {id:4,name:"Bilal Ahmed",email:"bilal@brightvision.edu",subject:"Urdu",classes:"Class 3",status:"Active"},
 {id:5,name:"Hina Qureshi",email:"hina@brightvision.edu",subject:"Islamiat",classes:"Class 4",status:"Active"},
 {id:6,name:"Kamran Yousuf",email:"kamran@brightvision.edu",subject:"Computer Science",classes:"Class 5, Class 6",status:"Active"},
 {id:7,name:"Nadia Farooq",email:"nadia@brightvision.edu",subject:"Social Studies",classes:"Class 6",status:"Inactive"},
 {id:8,name:"Rehan Aslam",email:"rehan@brightvision.edu",subject:"Mathematics",classes:"Class 7",status:"Active"},
];
const attendance:Attendance[] = students.map((s,i)=>({id:s.id,student:s.name,className:s.className,section:s.section,status:i===2?"Absent":i===4?"Late":"Present"}));
const fees:Fee[] = students.map((s,i)=>{const amount=3500+(i%4)*500;const status:Fee["status"]=i%5===0?"Overdue":i%3===0?"Pending":"Paid";return{id:s.id,student:s.name,invoice:`RCP-${1001+i}`,amount,paid:status==="Paid"?amount:status==="Pending"?0:0,due:status==="Overdue"?"10/07/2026":"25/08/2026",status}});
const nav = [["Dashboard",LayoutDashboard],["Students",GraduationCap],["Teachers",Users],["Classes",BookOpen],["Subjects",BookOpen],["Attendance",ClipboardCheck],["Fees",WalletCards],["Exams & Results",BarChart3],["Timetable",CalendarDays],["Notices",Bell],["Reports",BarChart3],["Settings",Settings]] as const;

export default function AppNext(){
 const [user,setUser]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem("bv_user")||"null")}catch{return null}});
 if(!user)return <Login onLogin={u=>{localStorage.setItem("bv_user",JSON.stringify(u));setUser(u)}}/>;
 return <Portal user={user} logout={()=>{localStorage.removeItem("bv_user");setUser(null)}}/>;
}
function Login({onLogin}:{onLogin:(u:any)=>void}){const[email,setEmail]=useState("admin@brightvision.edu"),[password,setPassword]=useState("admin123"),[error,setError]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();const u=users.find(x=>x.email===email.trim().toLowerCase()&&x.password===password);if(!u){setError("Invalid email or password. Demo admin: admin@brightvision.edu / admin123");return}onLogin(u)};return <div className="login-page"><div className="login-card"><div className="login-brand"><div className="logo big">BV</div><div><h1>Bright Vision</h1><span>English School</span></div></div><h2>Welcome back</h2><p className="muted">Sign in to School Management System</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><div className="login-options"><label className="check"><input type="checkbox" defaultChecked/> Remember me</label><button type="button" className="link">Forgot password?</button></div>{error&&<div className="error">{error}</div>}<button className="primary full">Login</button></form><div className="demo-box"><strong>Demo accounts</strong><span>Admin · Teacher · Accountant · Student · Parent</span></div></div></div>}
function Portal({user,logout}:{user:any;logout:()=>void}){const[open,setOpen]=useState(true),[active,setActive]=useState("Dashboard");const canWrite=user.role==="admin"||user.role==="teacher";return <div className="app"><aside className={`sidebar ${open?"":"collapsed"}`}><div className="brand"><div className="logo">BV</div>{open&&<div><strong>Bright Vision</strong><span>English School</span></div>}</div><nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><Icon size={19}/>{open&&label}</button>)}</nav><div className="sidebar-bottom"><div className="school-mini"><strong>{open?user.name:""}</strong>{open&&<span>{user.role}</span>}</div><button className="logout" onClick={logout}><LogOut size={19}/>{open&&"Logout"}</button></div></aside><main className="main"><header><button className="icon-btn" onClick={()=>setOpen(!open)}>{open?<ChevronLeft/>:<Menu/>}</button><div className="header-title"><span>Bright Vision English School</span><small>Academic Session 2026 – 2027</small></div><button className="icon-btn"><Bell size={20}/></button></header><section className="content">{active==="Dashboard"?<Dashboard user={user}/>:active==="Students"?<StudentsPage canWrite={canWrite}/>:active==="Teachers"?<TeachersPage canWrite={user.role==="admin"}/>:active==="Attendance"?<AttendancePage canWrite={canWrite}/>:active==="Fees"?<FeesPage canWrite={user.role==="admin"||user.role==="accountant"}/>:<Placeholder title={active}/>}</section></main></div>}
function Dashboard({user}:{user:any}){return <><div className="page-head"><div><h1>Dashboard</h1><p>Welcome back, {user.name}. Here is your school overview.</p></div></div><div className="stats"><Stat title="Total Students" value="486"/><Stat title="Total Teachers" value="8"/><Stat title="Total Classes" value="8"/><Stat title="Today's Attendance" value="92%"/><Stat title="Fee Collection" value="PKR 184,500"/><Stat title="Pending Fees" value="PKR 96,000"/></div><div className="grid"><div className="panel"><h2>Attendance Overview</h2><div className="attendance"><b>92%</b><span>Present today</span><div className="bar"><i style={{width:"92%"}}/></div><small>Present 447 · Late 18 · Absent 21</small></div></div><div className="panel"><h2>Fee Overview</h2><div className="fee-row"><span>Collected</span><b>PKR 184,500</b></div><div className="fee-row"><span>Pending</span><b>PKR 72,000</b></div><div className="fee-row"><span>Overdue</span><b>PKR 24,000</b></div></div></div></>}
function StudentsPage({canWrite}:{canWrite:boolean}){const[data,setData]=useState(students),[q,setQ]=useState(""),[show,setShow]=useState(false),[edit,setEdit]=useState<Student|null>(null);const filtered=useMemo(()=>data.filter(s=>`${s.name} ${s.father} ${s.className}`.toLowerCase().includes(q.toLowerCase())),[data,q]);return <><Head title="Students" text="Manage student records, classes and admission details." add={canWrite?()=>{setEdit(null);setShow(true)}:undefined}/><div className="panel table-panel"><Toolbar q={q} setQ={setQ} count={filtered.length}/><div className="table-wrap"><table><thead><tr><th>Student</th><th>Father</th><th>Class</th><th>Roll</th><th>Phone</th><th>Status</th>{canWrite&&<th>Actions</th>}</tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>BV-S-{String(s.id).padStart(4,"0")}</small></td><td>{s.father}</td><td>{s.className} · {s.section}</td><td>{s.roll}</td><td>{s.phone}</td><td><Badge value={s.status}/></td>{canWrite&&<td><Actions edit={()=>{setEdit(s);setShow(true)}} del={()=>setData(x=>x.filter(v=>v.id!==s.id))}/></td>}</tr>)}</tbody></table></div></div>{show&&<StudentModal item={edit} close={()=>setShow(false)} save={s=>{setData(x=>s.id?x.map(v=>v.id===s.id?s:v):[...x,{...s,id:Date.now()}]);setShow(false)}}/>}</>}
function TeachersPage({canWrite}:{canWrite:boolean}){const[data,setData]=useState(teachers),[q,setQ]=useState(""),[show,setShow]=useState(false),[edit,setEdit]=useState<Teacher|null>(null);const filtered=data.filter(x=>`${x.name} ${x.subject} ${x.email}`.toLowerCase().includes(q.toLowerCase()));return <><Head title="Teachers" text="Manage teaching staff and assignments." add={canWrite?()=>{setEdit(null);setShow(true)}:undefined}/><div className="panel table-panel"><Toolbar q={q} setQ={setQ} count={filtered.length}/><div className="table-wrap"><table><thead><tr><th>Teacher</th><th>Email</th><th>Subject</th><th>Classes</th><th>Status</th>{canWrite&&<th>Actions</th>}</tr></thead><tbody>{filtered.map(t=><tr key={t.id}><td><strong>{t.name}</strong></td><td>{t.email}</td><td>{t.subject}</td><td>{t.classes}</td><td><Badge value={t.status}/></td>{canWrite&&<td><Actions edit={()=>{setEdit(t);setShow(true)}} del={()=>setData(x=>x.filter(v=>v.id!==t.id))}/></td>}</tr>)}</tbody></table></div></div>{show&&<TeacherModal item={edit} close={()=>setShow(false)} save={t=>{setData(x=>t.id?x.map(v=>v.id===t.id?t:v):[...x,{...t,id:Date.now()}]);setShow(false)}}/>}</>}
function AttendancePage({canWrite}:{canWrite:boolean}){const[data,setData]=useState(attendance),[filter,setFilter]=useState("All");const counts={Present:data.filter(x=>x.status==="Present").length,Absent:data.filter(x=>x.status==="Absent").length,Late:data.filter(x=>x.status==="Late").length};const shown=filter==="All"?data:data.filter(x=>x.status===filter);return <><Head title="Attendance" text="Mark and review today's student attendance."/><div className="stats"><Stat title="Present" value={String(counts.Present)}/><Stat title="Late" value={String(counts.Late)}/><Stat title="Absent" value={String(counts.Absent)}/><Stat title="Attendance Rate" value={`${Math.round(counts.Present/data.length*100)}%`}/></div><div className="panel table-panel"><div className="table-toolbar"><div className="filters">{["All","Present","Late","Absent"].map(x=><button key={x} className={filter===x?"active-filter":"secondary"} onClick={()=>setFilter(x)}>{x}</button>)}</div><span>{new Date().toLocaleDateString("en-GB")}</span></div><div className="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Section</th><th>Attendance</th>{canWrite&&<th>Action</th>}</tr></thead><tbody>{shown.map(a=><tr key={a.id}><td><strong>{a.student}</strong></td><td>{a.className}</td><td>{a.section}</td><td><Badge value={a.status}/></td>{canWrite&&<td><select value={a.status} onChange={e=>setData(x=>x.map(v=>v.id===a.id?{...v,status:e.target.value as Attendance["status"]}:v))}><option>Present</option><option>Late</option><option>Absent</option></select></td>}</tr>)}</tbody></table></div></div></>}
function FeesPage({canWrite}:{canWrite:boolean}){const[data,setData]=useState(fees),[q,setQ]=useState("");const shown=data.filter(x=>`${x.student} ${x.invoice} ${x.status}`.toLowerCase().includes(q.toLowerCase()));const collected=data.reduce((n,x)=>n+x.paid,0),pending=data.filter(x=>x.status==="Pending").reduce((n,x)=>n+x.amount,0),overdue=data.filter(x=>x.status==="Overdue").reduce((n,x)=>n+x.amount,0);return <><Head title="Fees" text="Track invoices, collections, pending and overdue fees."/><div className="stats"><Stat title="Collected" value={`PKR ${collected.toLocaleString()}`}/><Stat title="Pending" value={`PKR ${pending.toLocaleString()}`}/><Stat title="Overdue" value={`PKR ${overdue.toLocaleString()}`}/><Stat title="Invoices" value={String(data.length)}/></div><div className="panel table-panel"><Toolbar q={q} setQ={setQ} count={shown.length}/><div className="table-wrap"><table><thead><tr><th>Student</th><th>Invoice</th><th>Amount</th><th>Paid</th><th>Due Date</th><th>Status</th>{canWrite&&<th>Action</th>}</tr></thead><tbody>{shown.map(f=><tr key={f.id}><td><strong>{f.student}</strong></td><td>{f.invoice}</td><td>PKR {f.amount.toLocaleString()}</td><td>PKR {f.paid.toLocaleString()}</td><td>{f.due}</td><td><Badge value={f.status}/></td>{canWrite&&<td>{f.status!=="Paid"&&<button className="primary small-btn" onClick={()=>setData(x=>x.map(v=>v.id===f.id?{...v,paid:v.amount,status:"Paid"}:v))}>Mark Paid</button>}</td>}</tr>)}</tbody></table></div></div></>}
function Head({title,text,add}:{title:string;text:string;add?:()=>void}){return <div className="page-head"><div><h1>{title}</h1><p>{text}</p></div>{add&&<button className="primary" onClick={add}><Plus size={17}/> Add {title.slice(0,-1)}</button>}</div>}
function Toolbar({q,setQ,count}:{q:string;setQ:(x:string)=>void;count:number}){return <div className="table-toolbar"><div className="search"><Search size={17}/><input placeholder="Search..." value={q} onChange={e=>setQ(e.target.value)}/></div><span>{count} records</span></div>}
function Actions({edit,del}:{edit:()=>void;del:()=>void}){return <div className="actions"><button className="icon-btn small" onClick={edit}><Pencil size={15}/></button><button className="icon-btn small danger" onClick={()=>{if(confirm("Delete this record? This action cannot be undone."))del()}}><Trash2 size={15}/></button></div>}
function Badge({value}:{value:string}){return <span className={`badge ${value.toLowerCase()}`}>{value}</span>}
function Stat({title,value}:{title:string;value:string}){return <div className="stat"><span>{title}</span><strong>{value}</strong></div>}
function Placeholder({title}:{title:string}){return <><Head title={title} text={`${title} module is ready for the next development phase.`}/><div className="panel empty"><h2>{title}</h2><p>Core navigation is connected. This module will be expanded with full CRUD, filters, reports and Supabase services.</p></div></>}
function StudentModal({item,close,save}:{item:Student|null;close:()=>void;save:(x:Student)=>void}){const[f,setF]=useState<Student>(item||{id:0,name:"",father:"",className:"Class 1",section:"A",roll:"",phone:"",status:"Active"});return <Modal title={item?"Edit Student":"Add Student"} close={close}><form onSubmit={e=>{e.preventDefault();save(f)}}><Fields fields={[["name","Full Name"],["father","Father Name"],["className","Class"],["section","Section"],["roll","Roll Number"],["phone","Phone"]]} data={f} setData={setF}/><ActionsFooter close={close}/></form></Modal>}
function TeacherModal({item,close,save}:{item:Teacher|null;close:()=>void;save:(x:Teacher)=>void}){const[f,setF]=useState<Teacher>(item||{id:0,name:"",email:"",subject:"",classes:"",status:"Active"});return <Modal title={item?"Edit Teacher":"Add Teacher"} close={close}><form onSubmit={e=>{e.preventDefault();save(f)}}><Fields fields={[["name","Full Name"],["email","Email"],["subject","Subject"],["classes","Assigned Classes"]]} data={f} setData={setF}/><ActionsFooter close={close}/></form></Modal>}
function Fields({fields,data,setData}:{fields:string[][];data:any;setData:(x:any)=>void}){return <div className="form-grid">{fields.map(([key,label])=><label key={key}>{label}<input value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})} required/></label>)}</div>}
function ActionsFooter({close}:{close:()=>void}){return <div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save</button></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:any}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{title}</h2><p>Enter the required information below.</p></div><button className="icon-btn" onClick={close}><X size={20}/></button></div>{children}</div></div>}
